import { assertEquals } from "@std/assert";
import { traverse, toGrid} from "./main.ts";

const strState1 = `
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
`

Deno.test(function navigateTest() {
  const grid = toGrid(strState1)
  const visitedPositions = traverse(grid)
  assertEquals(visitedPositions, 41)
})
